seed: 42

fixed_params:
  model: "lenet"
  dataset: "mnist"
  epochs: 50
  num_repeats: 1
  optimizer_name: "adamw"
  lr: 0.01
  weight_decay: 5e-4
  partial_frozen_slt: true
  m_init_method: "epl"
  ep_algo: "global_ep"
  scaling_rate: 1.0
  batch_size: 256
# tunable parameters (unconstrained)
params:
  pruned_frozen: <float>
  pruned_frozen_space: [0.0, 5.0]  # continuous range
  pruned_frozen_type: "continuous"
  locked_frozen: <float>
  locked_frozen_space: [0.0, 5.0]  # continuous range
  locked_frozen_type: "continuous"
  prune_nfrozen: <float>
  prune_nfrozen_space: [0.0, 5.0]  # continuous range
  prune_nfrozen_type: "continuous"
  lock_nfrozen: <float>
  lock_nfrozen_space: [0.0, 5.0]  # continuous range
  lock_nfrozen_type: "continuous"

  # Derived parameters (will be calculated from unconstrained parameters)
  pruning_rate: <float>
  p_ratio: <float>
  r_ratio: <float>

  num_bayes_layers: <int>
  num_bayes_layers_space: [1, 2, 3]  # discrete range for integer
  num_bayes_layers_type: "discrete"  # "discrete" or "continuous"
  dropout_rate: <float>
  dropout_rate_space: [0.05, 0.5]  # continuous range
  dropout_rate_type: "continuous"  # "discrete" or "continuous"

# evaluation metrics
eval:
  accuracy: <float>
  ece: <float>
  ape: <float>
  flops: <float>
  memory: <float>

bayes_opt:
  iteration: <int>
  terminate: <bool>
  engine: <obj>
  score: <float>
  summary: <list>
  control:
    params: dict
    metrics: dict
    suggests: dict

  num_iter: 100
  seed: ((seed))
  tunable:
    pruned_frozen:
       value: ((params.pruned_frozen))
       space: ((params.pruned_frozen_space))
       type: ((params.pruned_frozen_type))
    locked_frozen:
       value: ((params.locked_frozen))
       space: ((params.locked_frozen_space))
       type: ((params.locked_frozen_type))
    prune_nfrozen:
       value: ((params.prune_nfrozen))
       space: ((params.prune_nfrozen_space))
       type: ((params.prune_nfrozen_type))
    lock_nfrozen:
       value: ((params.lock_nfrozen))
       space: ((params.lock_nfrozen_space))
       type: ((params.lock_nfrozen_type))
    num_bayes_layers:
       value: ((params.num_bayes_layers))
       space: ((params.num_bayes_layers_space))
       type: ((params.num_bayes_layers_type))
    dropout_rate:
       value: ((params.dropout_rate))
       space: ((params.dropout_rate_space))
       type: ((params.dropout_rate_type))

  metrics:
    accuracy: ((eval.accuracy))
    ece: ((eval.ece))
    ape: ((eval.ape))
    flops: ((eval.flops))
    memory: ((eval.memory))

  score_weights:
    accuracy:
      weight: 0.4
      base: 100
    ece:
      weight: 0.2
      base: -20
    ape:
      weight: 0.2
      base: 1.0
    flops:
      weight: 0.1
      base: -40
    memory:
      weight: 0.1
      base: -0.0010
